#!/bin/bash

check() {
	local url=$(echo $1 | awk -F, '{print $1}')
	curl -m 10 -s -o "/dev/null" $url
	if [ $? -ne 0 ] ; then
		echo "$1" | awk -F, -v OFS=, -v INDEX=2 '{$INDEX="no"; print }'
	else
		echo "$1" | awk -F, -v OFS=, -v INDEX=2 '{$INDEX="yes"; print }'
	fi
}

file="$1"
result="$(basename ${file} .csv).result.csv"

rm -rf $result

sed 1d $file | while read -r line
do
	check "$line" >> $result
done

